
//
//Nguyen Khac Huy - 2280601183
//Have a nice day
//
package readallfileoffolder;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author khach
 */
public class frmReadListFile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmReadListFile.class.getName());

    /**
     * Creates new form frmReadListFile
     */
    public frmReadListFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcPath = new javax.swing.JFileChooser();
        txtPath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLietKe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsFile = new javax.swing.JList<>();
        btnTest = new javax.swing.JButton();
        txtKyTu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnChonPath = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập path: ");

        btnLietKe.setText("Liệt Kê DS file");
        btnLietKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLietKeActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lsFile);

        btnTest.setText("Test1");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        txtKyTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKyTuActionPerformed(evt);
            }
        });

        jLabel2.setText("Loại KTu:");

        btnChonPath.setText("Chọn Path");
        btnChonPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnTest))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLietKe, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKyTu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChonPath))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnChonPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLietKe)
                    .addComponent(txtKyTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTest)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLietKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLietKeActionPerformed
        //=>bd
//        File dir=new File(txtPath.getText());
//        File dsFile[]=dir.listFiles();
//        if(dsFile==null){
//            JOptionPane.showMessageDialog(this, "Sai đường dẫn!!!");
//        }else{
//            try{
//                //tao nd cho list "dm"
//                DefaultListModel dm =new DefaultListModel();
//                for(int i=0;i<dsFile.length;i++){
//                    String fileName=dsFile[i].getName();
//                    //them filename for "dm"
//                    dm.addElement(fileName);
//                }
//                //Them all namefile vao ls-Modal
//                lsFile.setModel(dm);
//            }catch(Exception e){
//                JOptionPane.showMessageDialog(this, e.toString());
//            }
//        }

        //nd2
        File dir=new File(txtPath.getText());
        File []dsDir=dir.listFiles();
        if(dsDir==null){
            JOptionPane.showMessageDialog(null, "Sai Path: ");
            return;
        }
        try{
            //tao dm chua nd
            DefaultListModel dm=new DefaultListModel();
            
            //get KT Loai
            //bo luon " "spane 2 dau
            String kyTu=txtKyTu.getText().trim();
            //System.out.println("kyTu: "+kyTu+"|");//kyTu: |
            
            for(int i=0;i<dsDir.length;i++){
                //khiK.tu = empty|->Lay het
                if(kyTu.isEmpty()){
                    dm.addElement(dsDir[i].getName());
                }else{
                    //1. Loc Bo
                    //khiK.tu != empty|->Lay all file ko chua KyTu
//                    if(dsDir[i].getName().contains(kyTu)==false){
//                        dm.addElement(dsDir[i].getName());
//                    }
                    
                    //2. Loc Lay
                    if(dsDir[i].getName().contains(kyTu)==true){
                        dm.addElement(dsDir[i].getName());
                    }
                }   
            }
            //them nd
            lsFile.setModel(dm);
            System.out.println("SL fileName: "+dsDir.length);
            //Empty=0, 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ERRPR: "+e);
        }
        
        
    }//GEN-LAST:event_btnLietKeActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        String myName="Nguyễn Khắc Huy";
        String kt="uy";
        JOptionPane.showMessageDialog(null, myName.contains(kt));
        
        
    }//GEN-LAST:event_btnTestActionPerformed

    private void txtKyTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKyTuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKyTuActionPerformed

    private void btnChonPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonPathActionPerformed
        //C1: Chon File
//        //show fc+ lay KQ
//        int result=fcPath.showDialog(this, "Chọn");
//        //Neu chon file
//        if(result==JFileChooser.APPROVE_OPTION){
//            //0 | 0
//            File file =fcPath.getSelectedFile();
//            String path=file.getAbsolutePath();
//            System.out.println(path);
//            //path: D:\3_Study_Eve.....(File)
//        }
        
        //C2: Chon Folder
        //add Mode|->Chi chon Folder
        fcPath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //show fc+ lay KQ
        int result=fcPath.showDialog(this, "Chọn");
        //Neu chon file
        if(result==JFileChooser.APPROVE_OPTION){
            //0 | 0
            File file =fcPath.getSelectedFile();
            String path=file.getAbsolutePath();
            //dan nd for txtPath
            txtPath.setText(path);
            //System.out.println(path);
            //path: D:\3_Study_Eve.....(Folder)
        }
        
    }//GEN-LAST:event_btnChonPathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmReadListFile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonPath;
    private javax.swing.JButton btnLietKe;
    private javax.swing.JButton btnTest;
    private javax.swing.JFileChooser fcPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lsFile;
    private javax.swing.JTextField txtKyTu;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
